findAllUsers = SELECT * FROM users
insertUser = INSERT INTO users (name, age) VALUES (?, ?)
createTable = CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), age INT)